---
abstract: 'A Simple Interface to Template Toolkit'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Template::Toolkit::Simple
name: Template-Toolkit-Simple
no_index:
  directory:
    - inc
    - t
recommends:
  YAML::XS: 0
requires:
  Template: 0
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ingydotnet/template-toolkit-simple-pm.git
version: 0.12
